# Generated by Django 5.2 on 2025-04-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriNow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='planos/%Y/%m/%d/')),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('nutricionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_criados', to='nutriNow.nutricionista')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_alimentares', to='nutriNow.paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='plano_alimentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_do_plano', to='nutriNow.planoalimentar'),
        ),
    ]
