# Generated by Django 5.2 on 2025-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriNow', '0002_planoalimentar_alter_paciente_plano_alimentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='diario_alimentar',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
