# Generated by Django 5.2 on 2025-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriNow', '0003_paciente_diario_alimentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricionista',
            name='horarios_disponiveis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
