# Generated by Django 5.2 on 2025-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriNow', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
