# Generated by Django 5.2 on 2025-05-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutriNow', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
